USE [master] 
GO

/****** Object:  Database [Reconnect_DCG]    Script Date: 01/09/2020 05:31:45 p. m. ******/
CREATE DATABASE [Reconnect_DCG]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Reconnect_DCG', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Reconnect_DCG.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Reconnect_DCG_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Reconnect_DCG_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Reconnect_DCG].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Reconnect_DCG] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Reconnect_DCG] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Reconnect_DCG] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Reconnect_DCG] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Reconnect_DCG] SET ARITHABORT OFF 
GO

ALTER DATABASE [Reconnect_DCG] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Reconnect_DCG] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Reconnect_DCG] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Reconnect_DCG] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Reconnect_DCG] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Reconnect_DCG] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Reconnect_DCG] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Reconnect_DCG] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Reconnect_DCG] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Reconnect_DCG] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Reconnect_DCG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Reconnect_DCG] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Reconnect_DCG] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Reconnect_DCG] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Reconnect_DCG] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Reconnect_DCG] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Reconnect_DCG] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Reconnect_DCG] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Reconnect_DCG] SET  MULTI_USER 
GO

ALTER DATABASE [Reconnect_DCG] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Reconnect_DCG] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Reconnect_DCG] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Reconnect_DCG] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Reconnect_DCG] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Reconnect_DCG] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Reconnect_DCG] SET  READ_WRITE 
GO


